sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update 1.1.2
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit
